### ISSUE TITLE
x-ua-compatible tag is deprecated and charset tag has more efficient alternative.

### ISSUE THREAD

**Issue by DitheringIdiot** [lewdev/meta-tag-gen#4]
## x-ua-compatible

Cool site. I just wanted to point out that Microsoft and Mozilla both recommend no longer using this tag:

```
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
```
Instead they instruct that correctly declaring `<!doctype html>` will solve any issues relating to backwards compatibility in `Internet Explorer`

- [Microsoft's recommendation](https://docs.microsoft.com/en-gb/previous-versions/windows/internet-explorer/ie-developer/dev-guides/bg182625(v=vs.85)#document-mode-changes)
- [Mozilla's recommendation](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode#how_does_mozilla_determine_which_mode_to_use.3f)

A more in-depth and better explanation on why it shouldn't be used can be found here:  https://hsivonen.iki.fi/doctype/

## charset=utf-8

This tag can be simplified:

```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
```

to this:

```
<meta charset="utf-8">
```

I'm surprised that moz recommend the first version in the [article you linked](https://moz.com/blog/the-ultimate-guide-to-seo-meta-tags). Since in the source code of the site, they use the second shorter version!

Anyway, I hope this isn't too pedantic, I'm just trying to save your users a few bytes.

**Comment by lewdev** [comment]
Thank you so much. I definitely would rather use Mozilla and Microsoft's recommendation. My intention for meta-tag-gen was to use the best recommendation with sources. I was confused since I have seen your recommendation but only could find the other recommendation in an article. I probably didn't look very deep though.

I'll make the update. Something I've put off for a very long time.

**Comment by DitheringIdiot** [comment]
Honestly, I’ve spent the last week deep in the weeds of x-ua-compatible, there’s a lot of conflicting information. Glad to be of help! It’s a cool project.
